# Generated by Django 5.2.8 on 2025-12-01 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='majortask',
            unique_together={('user', 'user_task_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('major_task', 'task_subtask_id')},
        ),
    ]
